print ("Hello World!")
print ("123##$$")
print ("I like typing this.")
print ("This is fun.")
print ('Yay! Printing.')
print ("I'd much rather you 'not'.")
print ('I "said" do not touch this.')
print (2+5)
print ("hello all",2+5)
print ("is it true? that 2<5")
print ("Is it true that 3 + 2 < 5 - 7?")
print ((3 + 2 )> (5 - 7))
print (3 + 2 + 1 - 5 + 4 % 2 - 1 / 4 + 6)
print ("is it greator than or less than", 5>-2)
print ("Is it greater?", 5 > - 2)
print ("Is it greater or equal?", 5 >= - 2)
print ("Is it less or equal?", 5 <= -2 )